spring:
  application:
    name: DBAGENDA
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DBAGENDA?serverTimezone=UTC
    username: root
    password: $F3r13n$
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED:*}
checkBenutzerEinsatz:
  delay: 0 0 6 * * *