CREATE DATABASE DBAGENDA;

USE DBAGENDA;

CREATE TABLE EINTRAG
(
	EINTRAGID INT NOT NULL,
	TITEL VARCHAR(255) NOT NULL,
	BESCHREIBUNG VARCHAR(255) NOT NULL,
	STARTDATUM DATE,
    ENDDATUM DATE,
    ORT VARCHAR(255),
    PRIMARY KEY (EINTRAGID)
);

CREATE TABLE TAG
(
	DATUM DATE,
    FK_EINTRAGID int,
    FOREIGN KEY (FK_EINTRAGID) REFERENCES EINTRAG(EINTRAGID)
);